apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"  # Keep this one
    # Removed the redundant annotation
  labels:
    app: webmvc
  name: eshop-webmvc-loopback
  namespace: default
spec:
  rules:
  - http: 
      paths:
      - backend:
          serviceName: webmvc
          servicePort: http
        path: /webmvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"  # Keep this one
    # Removed the redundant annotation
  labels:
    app: identity-api
  name: eshop-identity-api-loopback
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: identity
          servicePort: http
        path: /identity