{{- if .Values.ingress.enabled -}}
{{- if .Values.inf.k8s.local -}}
{{- $ingressPath := include "pathBase" . -}}  # Get base path
{{- $serviceName := .Values.app.svc.mvc }}  # Service name
{{- $name := include "webmvc.fullname" . -}}  # Fullname for Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-local
  labels:
    app: {{ template "webmvc.name" . }}
    chart: {{ template "webmvc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}    
{{- if .Values.inf.mesh.enabled }} 
{{- with .Values.ingress.mesh.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}  # Combined path definition with pathType
        pathType: Prefix  # Optional, can be customized in values.yaml
        backend:
          service:  # Updated syntax for newer Kubernetes versions
            name: {{ $serviceName }}  # Corrected line
            port: http  # Optional line (default port is http)
{{- end -}}
{{- end -}}